### PR TITLE
Mintable ERC20 & ERC1155 Predicate [ READY FOR REVIEW ]

### PR DESCRIPTION
**Pull request by itzmeanjan**
## changes

- Mintable ERC20 & ERC1155 Predicates
- Along with respective default child token contracts
- Also respective dummy root token contracts

### CODE REVIEW

**Review by imyourm8 — CHANGES_REQUESTED** [review]
Everything looks good, I only miss a set of tests for the new predicates.

**Comment by itzmeanjan** [comment]
> Everything looks good, I only miss a set of tests for the new predicates.

Ok, I'll write some.

**Comment by itzmeanjan** [comment]
Wrote some test cases, if you could review @jdkanani , @imyourm8

**Review by coinsandsteeldev — APPROVED** [review]
Looks good to me.

**Comment by itzmeanjan** [comment]
Deployment done. Details : https://github.com/maticnetwork/static/pull/42

**Review by jdkanani — APPROVED** [review]

**Review by imyourm8 — APPROVED** [review]

**Comment by VogtAI** [comment]
Is there any documentation for mintable ERC20 predicates? I was under the impression these were used to have token minting on Matic. Shouldn't the rootChainManager then be able to mint tokens on the RootChain when minted tokens on the childChain are locked up? In RootToken/DummyMintableERC20.sol _msgSender() has the PREDICATE_ROLE instead of the rootChainManager. Can someone please explain to me how this is supposed work?

**Pull request merged**
